/**
 * Bundles every module under `facets/` to a string and writes
 * `generated/facets.ts`, the one file the root imports its facet code from.
 *
 * `cloudflare:workers` stays external — the runtime provides it inside the
 * loaded worker — and everything else (TinyBase included) is inlined, since a
 * dynamic worker has no `node_modules`. The version is a hash of the bundle, so
 * the root's loader key changes exactly when the code does, which is what lets
 * `reload` swap a facet's class while its state persists.
 */
import {readdirSync, writeFileSync, mkdirSync} from 'node:fs';
import {join, basename} from 'node:path';

const here = import.meta.dir;
const facets: Record<string, {version: string; code: string}> = {};
for (const file of readdirSync(join(here, 'facets')).filter((f) => f.endsWith('.ts')).sort()) {
  const result = await Bun.build({
    entrypoints: [join(here, 'facets', file)],
    format: 'esm',
    target: 'browser',
    external: ['cloudflare:workers'],
    minify: false,
  });
  if (!result.success) {
    for (const log of result.logs) console.error(String(log));
    process.exit(1);
  }
  const code = await result.outputs[0]!.text();
  const hasher = new Bun.CryptoHasher('sha256');
  hasher.update(code);
  facets[basename(file, '.ts')] = {version: hasher.digest('hex').slice(0, 12), code};
}
mkdirSync(join(here, 'generated'), {recursive: true});
writeFileSync(
  join(here, 'generated', 'facets.ts'),
  '// Generated by build-facets.ts — do not edit. One entry per file under facets/.\n' +
    'export const FACETS: Record<string, {version: string; code: string}> = ' +
    JSON.stringify(facets, null, 2) +
    ';\n',
);
console.log(Object.entries(facets).map(([n, f]) => `${n}@${f.version} ${(f.code.length / 1024).toFixed(0)} KiB`).join('\n'));
